### PR TITLE
Refactor

### LINKED ISSUE #3: Item Dupe Glitch - Creative Destructor/Constructor
Mod Version: cabletiers-1.16x-0.24.jar

Same issue as reported here: https://github.com/AllTheMods/ATM-6/issues/1984

The issue occurs when you remove and place a block quickly using the Creative Destructor and Constructor.

Video showcase:
https://www.youtube.com/watch?v=iprCPK4pBRc

### PR DESCRIPTION
**Pull request by iTitus**
- [x] Exporter
- [x] Importer
- [x] Constructor
- [x] Destructor

Closes #3

### CODE REVIEW

**Comment by iTitus** [comment]
I cannot reproduce #3 in this branch, I might have fixed it? idk

**Comment by starforcraft** [comment]
lol nice

**Comment by starforcraft** [comment]
Did you test Server too? Because maybe the dupe only works on server

**Comment by iTitus** [comment]
If you push your changes made in 0.24 to GitHub I can merge those into this PR.

**Comment by iTitus** [comment]
Just tested this in ATM6 1.7.1: #3 is fixed. I don't know how, but it is...

**Comment by cdgamedev** [comment]
> Just tested this in ATM6 1.7.1: #3 is fixed. I don't know how, but it is...

That sounds like the majority of programming tbf.

Glad to hear its fixed tho! Thanks (:

**Comment by starforcraft** [comment]
> If you push your changes made in 0.24 to GitHub somewhere (even other branch) I can merge those into this PR.

Did I really forget to push that? Oof The Problem is im still on vacation and my pc isn’t with me

**Comment by starforcraft** [comment]
But really really thanks!

**Pull request merged**
